### ISSUE TITLE
Unable to run makepkg -s 

### ISSUE THREAD

**Issue by charlesbrandt** [endeavour/DellXps7390-2in1-Manjaro-Linux-Fixes#4]
Thank you for compiling this set of fixes. I tried following the instructions with manjaro-xfce-18.1.0-stable-x86_64. 

I get the following when I get to step 4. Run ```makepkg -s``` to build the kernel packages.

```
$ makepkg -s
==> Making package: linux53 5.3.1-1 (Mon 23 Sep 2019 02:45:13 AM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
warning: database file for 'core' does not exist (use '-Sy' to download)
warning: database file for 'extra' does not exist (use '-Sy' to download)
warning: database file for 'community' does not exist (use '-Sy' to download)
warning: database file for 'multilib' does not exist (use '-Sy' to download)
==> Installing missing dependencies...
[sudo] password for account: 
warning: database file for 'core' does not exist (use '-Sy' to download)
warning: database file for 'extra' does not exist (use '-Sy' to download)
warning: database file for 'community' does not exist (use '-Sy' to download)
warning: database file for 'multilib' does not exist (use '-Sy' to download)
error: target not found: xmlto
error: target not found: docbook-xsl
error: target not found: elfutils
==> ERROR: 'pacman' failed to install missing dependencies.
```

I do not have a network connection at this point. I tried: 

    sudo cp -r linux-firmware /lib/firmware/ 

After rebooting I still don't have a network connection. 

Any clues about what I'm doing wrong?

**Comment by endeavour** [comment]
Are you sure the copy command is correct? Presumably thats going to create a ```linux-firmware``` subdirectory under ```/lib/firmware```

**Comment by endeavour** [comment]
Note that you can always build the kernel on another machine and copy it (and the firmware files) across on a USB stick if that's easier.

**Comment by endeavour** [comment]
I think you want:
```sudo cp -r linux-firmware/* /lib/firmware/```

**Comment by charlesbrandt** [comment]
Thanks for the response. After compiling the new kernel on a VM with network access and then transferring over, everything works as expected. Thanks for making this available!
